/*
 * Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES.
 * All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "AddScalarTritonPlugin.h"

#include <cstdint>
#include <cstring>
#include <cuda.h>
#include <limits>
#include <memory>

// The ahead-of-time compiled Triton kernel. `add_scalar.h` is generated by the Makefile
// (`triton.tools.compile` then `triton.tools.link`) and is plain C without an `extern "C"` guard of
// its own, so the wrapper here is mandatory -- without it the link fails with an undefined
// reference to the C++-mangled name.
extern "C"
{
#include "add_scalar.h"
}

// A plugin library must export **both** `getCreators` and `setLoggerFinder`. Exporting only
// `getCreators` is not a link error and not a load error either: `loadLibrary` returns a handle and
// the creators are simply never registered, so the failure surfaces much later as
// "Cannot find plugin: AddScalarTriton, version: 1".
extern "C" void setLoggerFinder(nvinfer1::ILoggerFinder *finder) {}

namespace nvinfer1
{

AddScalarTritonPlugin::AddScalarTritonPlugin(float const scalar):
    mScalar(scalar)
{
    WHERE_AM_I();
}

IPluginCapability *AddScalarTritonPlugin::getCapabilityInterface(PluginCapabilityType type) noexcept
{
    WHERE_AM_I();
    switch (type)
    {
    case PluginCapabilityType::kBUILD:
        return static_cast<IPluginV3OneBuild *>(this);
    case PluginCapabilityType::kRUNTIME:
        return static_cast<IPluginV3OneRuntime *>(this);
    case PluginCapabilityType::kCORE:
        return static_cast<IPluginV3OneCore *>(this);
    }
    return nullptr;
}

IPluginV3 *AddScalarTritonPlugin::clone() noexcept
{
    WHERE_AM_I();
    try
    {
        std::unique_ptr<AddScalarTritonPlugin> p {std::make_unique<AddScalarTritonPlugin>(*this)};
        return p.release();
    }
    catch (...)
    {
        return nullptr;
    }
}

char const *AddScalarTritonPlugin::getPluginName() const noexcept
{
    WHERE_AM_I();
    return PLUGIN_NAME;
}

char const *AddScalarTritonPlugin::getPluginVersion() const noexcept
{
    WHERE_AM_I();
    return PLUGIN_VERSION;
}

char const *AddScalarTritonPlugin::getPluginNamespace() const noexcept
{
    WHERE_AM_I();
    return PLUGIN_NAMESPACE;
}

int32_t AddScalarTritonPlugin::configurePlugin(DynamicPluginTensorDesc const *in, int32_t nbInputs, DynamicPluginTensorDesc const *out, int32_t nbOutputs) noexcept
{
    WHERE_AM_I();
    if (in == nullptr || out == nullptr || nbInputs != 1 || nbOutputs != 1)
    {
        return -1;
    }
    return 0;
}

int32_t AddScalarTritonPlugin::getOutputDataTypes(DataType *outputTypes, int32_t nbOutputs, DataType const *inputTypes, int32_t nbInputs) const noexcept
{
    WHERE_AM_I();
    if (outputTypes == nullptr || inputTypes == nullptr || nbInputs != 1 || nbOutputs != 1)
    {
        return -1;
    }
    outputTypes[0] = inputTypes[0];
    return 0;
}

int32_t AddScalarTritonPlugin::getOutputShapes(DimsExprs const *inputs, int32_t nbInputs, DimsExprs const *shapeInputs, int32_t nbShapeInputs, DimsExprs *outputs, int32_t nbOutputs, IExprBuilder &exprBuilder) noexcept
{
    WHERE_AM_I();
    if (inputs == nullptr || outputs == nullptr || nbInputs != 1 || nbOutputs != 1)
    {
        return -1;
    }
    outputs[0].nbDims = inputs[0].nbDims;
    for (int i = 0; i < outputs[0].nbDims; ++i)
    {
        outputs[0].d[i] = inputs[0].d[i];
    }
    return 0;
}

bool AddScalarTritonPlugin::supportsFormatCombination(int32_t pos, DynamicPluginTensorDesc const *inOut, int32_t nbInputs, int32_t nbOutputs) noexcept
{
    WHERE_AM_I();
    if (inOut == nullptr || nbInputs != 1 || nbOutputs != 1 || pos < 0 || pos >= nbInputs + nbOutputs)
    {
        return false;
    }

    bool res {false};
    switch (pos)
    {
    case 0:
        // The kernel was compiled for `*fp32`, so only FP32 linear can be accepted. A Triton kernel
        // is specialized per dtype at AOT time: supporting FP16 too means compiling a second
        // variant, it is not a run-time decision.
        res = inOut[0].desc.type == DataType::kFLOAT && inOut[0].desc.format == TensorFormat::kLINEAR;
        break;
    case 1:
        res = inOut[1].desc.type == inOut[0].desc.type && inOut[1].desc.format == inOut[0].desc.format;
        break;
    default: // should NOT be here!
        break;
    }
    PRINT_FORMAT_COMBINATION();
    return res;
}

int32_t AddScalarTritonPlugin::getNbOutputs() const noexcept
{
    WHERE_AM_I();
    return 1;
}

size_t AddScalarTritonPlugin::getWorkspaceSize(DynamicPluginTensorDesc const *inputs, int32_t nbInputs, DynamicPluginTensorDesc const *outputs, int32_t nbOutputs) const noexcept
{
    WHERE_AM_I();
    return 0;
}

int32_t AddScalarTritonPlugin::getValidTactics(int32_t *tactics, int32_t nbTactics) noexcept
{
    WHERE_AM_I();
    return 0; // Only one AOT variant here; `plugin_gen.py` is the version with several
}

int32_t AddScalarTritonPlugin::getNbTactics() noexcept
{
    WHERE_AM_I();
    return 0;
}

char const *AddScalarTritonPlugin::getTimingCacheID() noexcept
{
    WHERE_AM_I();
    return nullptr;
}

int32_t AddScalarTritonPlugin::getFormatCombinationLimit() noexcept
{
    WHERE_AM_I();
    return 0;
}

char const *AddScalarTritonPlugin::getMetadataString() noexcept
{
    WHERE_AM_I();
    return nullptr;
}

int32_t AddScalarTritonPlugin::setTactic(int32_t tactic) noexcept
{
    WHERE_AM_I();
    return (tactic == 0) ? 0 : -1;
}

int32_t AddScalarTritonPlugin::onShapeChange(PluginTensorDesc const *in, int32_t nbInputs, PluginTensorDesc const *out, int32_t nbOutputs) noexcept
{
    WHERE_AM_I();
    if (in == nullptr || out == nullptr || nbInputs != 1 || nbOutputs != 1)
    {
        return -1;
    }
    for (int32_t i = 0; i < in[0].dims.nbDims; ++i)
    {
        if (in[0].dims.d[i] <= 0)
        {
            return -1;
        }
    }
    return 0;
}

int32_t AddScalarTritonPlugin::enqueue(PluginTensorDesc const *inputDesc, PluginTensorDesc const *outputDesc, void const *const *inputs, void *const *outputs, void *workspace, cudaStream_t stream) noexcept
{
    WHERE_AM_I();
    if (inputDesc == nullptr || outputDesc == nullptr || inputs == nullptr || outputs == nullptr || inputs[0] == nullptr || outputs[0] == nullptr)
    {
        return -1;
    }
    if (inputDesc[0].type != DataType::kFLOAT || outputDesc[0].type != DataType::kFLOAT)
    {
        return -1;
    }

    int64_t nElement64 {1};
    for (int32_t i = 0; i < inputDesc[0].dims.nbDims; ++i)
    {
        int32_t const dim = inputDesc[0].dims.d[i];
        nElement64 *= dim;
        if (dim <= 0 || nElement64 > std::numeric_limits<int32_t>::max())
        {
            return -1;
        }
    }

    // The whole point of the example: one call, no Triton, no Python, no JIT. The cubin is a byte
    // array inside this `.so` and the launcher is the generated `cuLaunchKernel` wrapper.
    // The return value must be checked: the linked dispatcher rejects unaligned pointers with
    // CUDA_ERROR_INVALID_VALUE *without launching anything*, which would otherwise leave the output
    // buffer untouched and look like a wrong kernel rather than a failed launch.
    CUresult const ret = add_scalar_default(stream, reinterpret_cast<CUdeviceptr>(inputs[0]), reinterpret_cast<CUdeviceptr>(outputs[0]), mScalar, static_cast<int32_t>(nElement64));
    if (ret != CUDA_SUCCESS)
    {
        return -1;
    }

    return (cudaGetLastError() == cudaSuccess) ? 0 : -1;
}

IPluginV3 *AddScalarTritonPlugin::attachToContext(IPluginResourceContext *context) noexcept
{
    WHERE_AM_I();
    try
    {
        // Load the cubin here rather than letting the generated launcher do it lazily on the first
        // `enqueue`: `cuModuleLoadData` binds to whatever CUDA context is current, and this is the
        // moment TensorRT hands over the context the engine will actually run in.
        load_add_scalar();
        return clone();
    }
    catch (...)
    {
        return nullptr;
    }
}

PluginFieldCollection const *AddScalarTritonPlugin::getFieldsToSerialize() noexcept
{
    WHERE_AM_I();
    try
    {
        mDataToSerialize.clear();
        mDataToSerialize.emplace_back(PluginField("scalar", &mScalar, PluginFieldType::kFLOAT32, 1));
        mFCToSerialize.nbFields = mDataToSerialize.size();
        mFCToSerialize.fields   = mDataToSerialize.data();
        return &mFCToSerialize;
    }
    catch (...)
    {
        return nullptr;
    }
}

AddScalarTritonPluginCreator::AddScalarTritonPluginCreator()
{
    WHERE_AM_I();
    mPluginAttributes.clear();
    mPluginAttributes.emplace_back(PluginField("scalar", nullptr, PluginFieldType::kFLOAT32, 1));
    mFC.nbFields = mPluginAttributes.size();
    mFC.fields   = mPluginAttributes.data();
}

char const *AddScalarTritonPluginCreator::getPluginName() const noexcept
{
    WHERE_AM_I();
    return PLUGIN_NAME;
}

char const *AddScalarTritonPluginCreator::getPluginVersion() const noexcept
{
    WHERE_AM_I();
    return PLUGIN_VERSION;
}

PluginFieldCollection const *AddScalarTritonPluginCreator::getFieldNames() noexcept
{
    WHERE_AM_I();
    return &mFC;
}

IPluginV3 *AddScalarTritonPluginCreator::createPlugin(char const *name, PluginFieldCollection const *fc, TensorRTPhase phase) noexcept
{
    WHERE_AM_I();
    try
    {
        float scalar {0.f};

        if (fc != nullptr && fc->fields != nullptr)
        {
            for (int32_t i = 0; i < fc->nbFields; ++i)
            {
                auto const fieldName(fc->fields[i].name);
                if (fieldName != nullptr && std::strcmp(fieldName, "scalar") == 0)
                {
                    if (fc->fields[i].data == nullptr || fc->fields[i].type != PluginFieldType::kFLOAT32 || fc->fields[i].length != 1)
                    {
                        return nullptr;
                    }
                    scalar = *static_cast<float const *>(fc->fields[i].data);
                }
            }
        }

        return new AddScalarTritonPlugin(scalar);
    }
    catch (...)
    {
        return nullptr;
    }
}

char const *AddScalarTritonPluginCreator::getPluginNamespace() const noexcept
{
    WHERE_AM_I();
    return PLUGIN_NAMESPACE;
}

} // namespace nvinfer1

extern "C" nvinfer1::IPluginCreatorV3One *const *getCreators(int32_t &nbCreators)
{
    nbCreators = 1;
    static nvinfer1::AddScalarTritonPluginCreator creator;
    static nvinfer1::IPluginCreatorV3One *const   pluginCreatorList[] = {&creator};
    return pluginCreatorList;
}
