# Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Put an ahead-of-time compiled OpenAI-Triton kernel inside a TensorRT plugin.

`../PythonPlugin/add_scalar_triton.py` already runs a Triton kernel from a plugin, but it is
a *Python* plugin calling Triton's JIT: the deployed process needs Python, Triton, and a compiler,
and the first `enqueue` pays for compilation.

This example takes the other path. `triton.tools.compile` compiles the kernel **ahead of time** into
C source with the cubin embedded as a byte array, `triton.tools.link` gives those specializations
stable symbol names, and an ordinary C++ `IPluginV3` calls the generated launcher. What ships is one
`.so`; at run time there is no Python, no Triton and no JIT.

+ case 1 -- the hand-written plugin.
+ case 2 -- the fp32-argument ABI bug in Triton's AOT output, reproduced and fixed.
+ case 3 -- the proof that the result needs neither Python nor Triton.
+ case 4 -- `plugin_gen.py`, which writes the whole plugin from a kernel + a spec, and turns several
  AOT variants of one kernel into TensorRT **tactics** so the builder times them and picks.
"""

import ctypes
import json
import os
import re
import subprocess
import sys
import tempfile
import time
from pathlib import Path

import numpy as np
import tensorrt as trt
from cuda.bindings import runtime as cudart
from scipy.special import erf
from tensorrt_cookbook import TRTWrapperV1, case_mark, check_array, get_plugin

import plugin_gen

SHAPE = [16, 512, 512]
SCALAR = 1.0
current_path = Path(__file__).parent
plugin_file = current_path / "AddScalarTritonPlugin.so"

input_data = {"inputT0": (np.arange(np.prod(SHAPE), dtype=np.float32).reshape(SHAPE) % 13 - 6)}

def build_and_run(plugin_file_list, plugin_info, trt_file, tag):
    """Build a one-layer engine around the plugin and run it."""
    tw = TRTWrapperV1(trt_file=trt_file, plugin_file_list=plugin_file_list)
    if tw.engine_bytes is None:
        # DETAILED is what makes `TacticValue` show up in the engine information later
        tw.builder_config.profiling_verbosity = trt.ProfilingVerbosity.DETAILED
        input_tensor = tw.network.add_input("inputT0", trt.float32, [-1, -1, -1])
        tw.profile.set_shape(input_tensor.name, [1, 1, 1], SHAPE, SHAPE)
        layer = tw.network.add_plugin_v3([input_tensor], [], get_plugin(plugin_info))
        layer.name = tag
        tensor = layer.get_output(0)
        tensor.name = "outputT0"
        tw.build([tensor])
        if trt_file is not None:
            tw.serialize_engine(trt_file)

    tw.setup(input_data, b_print_io=False)
    tw.infer(b_print_io=False)
    return tw.buffer["outputT0"][0], tw

@case_mark
def case_hand_written_plugin():
    """The AOT kernel called from a hand-written `IPluginV3`."""
    subprocess.run(["make", "all", "-j"], cwd=current_path, check=True, stdout=subprocess.DEVNULL)

    plugin_info = dict(
        name="AddScalarTriton",
        version="1",
        namespace="",
        argument_dict=dict(scalar=np.array([SCALAR], dtype=np.float32)),
        number_input_tensor=1,
        number_input_shape_tensor=0,
        plugin_api_version="3",
    )
    output, _ = build_and_run([plugin_file], plugin_info, Path("model-manual.trt"), "AddScalarTritonLayer")
    check_array(output, input_data["inputT0"] + SCALAR, True)

    # What the AOT step actually produced: C source with the cubin inlined, and symbol names that
    # no longer carry the hash (that is `triton.tools.link`'s job).
    generated_file_list = sorted(p.name for p in current_path.glob("add_scalar*.[ch]"))
    print(f"    generated by the Makefile: {generated_file_list}")
    print(f"    plugin .so size: {plugin_file.stat().st_size / 1024:.0f} KiB (the cubin is inside it)")
    return

@case_mark
def case_the_fp32_argument_trap():
    """Why the Makefile has a `sed` in it: an `fp32` kernel argument is silently read as garbage.

    `triton.tools.compile` declares an `fp32` kernel argument as `double` in the generated C, then
    puts `&scalar` into the `cuLaunchKernel` argument array -- where the kernel's parameter slot is
    4 bytes wide. The kernel therefore reads the **low half** of the double: for 1.0
    (0x3FF0000000000000) that is 0x00000000, i.e. `x + 0`. No error, no warning, wrong numbers.

    Both variants are built here and called directly through ctypes, no TensorRT involved.
    """
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        subprocess.run([sys.executable, "-m", "triton.tools.compile", str(current_path / "kernel.py"), "--kernel-name", "add_scalar_kernel", "--out-name", "k", "-o", str(temp_path / "k"), "--signature", "*fp32:16, *fp32:16, fp32, i32, 256", "--grid", "(n_element + 255) / 256, 1, 1"], check=True, capture_output=True)
        source_file = next(temp_path.glob("k.*.c"))
        header_file = next(temp_path.glob("k.*.h"))
        entry_point = re.search(r"CUresult (\w+)\(CUstream", header_file.read_text()).group(1)
        print(f"    generated C prototype: {re.search(r'CUresult .*', header_file.read_text()).group(0)}")

        n_element = 8
        host_input = np.arange(n_element, dtype=np.float32)
        for tag, b_patch in [("as generated (double)", False), ("after the sed (float) ", True)]:
            if b_patch:
                source_file.write_text(source_file.read_text().replace("double scalar", "float scalar"))
            library_file = temp_path / f"k-{b_patch}.so"
            subprocess.run(["gcc", "-shared", "-fPIC", "-O2", "-I/usr/local/cuda/include", str(source_file), "-o", str(library_file), "-L/usr/local/cuda/lib64/stubs", "-lcuda"], check=True, capture_output=True)

            launch = getattr(ctypes.CDLL(str(library_file)), entry_point)
            launch.restype = ctypes.c_int
            # The caller must match whatever the generated prototype says: `c_double` before the
            # patch, `c_float` after it. Getting this pair out of step is the same bug one level up.
            scalar_type = ctypes.c_float if b_patch else ctypes.c_double
            launch.argtypes = [ctypes.c_void_p, ctypes.c_ulonglong, ctypes.c_ulonglong, scalar_type, ctypes.c_int32]

            _, device_input = cudart.cudaMalloc(n_element * 4)
            _, device_output = cudart.cudaMalloc(n_element * 4)
            cudart.cudaMemcpy(device_input, host_input.ctypes.data, n_element * 4, cudart.cudaMemcpyKind.cudaMemcpyHostToDevice)
            return_code = launch(None, device_input, device_output, SCALAR, n_element)
            cudart.cudaDeviceSynchronize()
            host_output = np.empty(n_element, dtype=np.float32)
            cudart.cudaMemcpy(host_output.ctypes.data, device_output, n_element * 4, cudart.cudaMemcpyKind.cudaMemcpyDeviceToHost)
            cudart.cudaFree(device_input)
            cudart.cudaFree(device_output)

            print(f"    {tag}: launch returned {return_code}, x + {SCALAR} = {host_output}")
            if b_patch:
                assert np.allclose(host_output, host_input + SCALAR), "the patched launcher is still wrong"
            else:
                assert np.allclose(host_output, host_input), "the bug did not reproduce -- has Triton fixed it?"
    print("    -> the launch succeeds either way; only the numbers differ, which is the dangerous part")
    return

@case_mark
def case_no_python_no_triton_at_runtime():
    """The claim that AOT buys deployability, checked rather than asserted.

    The engine is rebuilt and run in a subprocess where importing `triton` raises. If anything in
    the plugin still reached back into Triton, this would fail.
    """
    script = ("import sys\n"
              "class Blocker:\n"
              "    def find_module(self, name, path=None):\n"
              "        if name == 'triton' or name.startswith('triton.'):\n"
              "            raise ImportError('triton is blocked on purpose')\n"
              "        return None\n"
              "sys.meta_path.insert(0, Blocker())\n"
              "import numpy as np, tensorrt as trt\n"
              "from tensorrt_cookbook import TRTWrapperV1, get_plugin\n"
              "import main\n"
              "out = main.build_and_run([main.plugin_file], dict(name='AddScalarTriton', version='1', namespace='',\n"
              "    argument_dict=dict(scalar=np.array([main.SCALAR], dtype=np.float32)),\n"
              "    number_input_tensor=1, number_input_shape_tensor=0, plugin_api_version='3'),\n"
              "    None, 'AddScalarTritonLayer')[0]\n"
              "assert np.allclose(out, main.input_data['inputT0'] + main.SCALAR), 'wrong result'\n"
              "assert 'triton' not in sys.modules, 'triton got imported after all'\n"
              "print('    subprocess: engine built and run with triton import blocked, result correct')\n")
    environment = dict(os.environ)
    environment["PYTHONPATH"] = os.pathsep.join([str(current_path)] + ([environment["PYTHONPATH"]] if environment.get("PYTHONPATH") else []))
    process = subprocess.run([sys.executable, "-c", script], cwd=current_path, env=environment, capture_output=True, text=True)
    print(process.stdout.strip() or process.stderr.strip()[-500:])
    assert process.returncode == 0, "the plugin still depends on Triton at run time"

    # And the .so itself: no libpython, no libtriton. Note `libnvinfer` is not there either -- a
    # plugin only implements interfaces, TensorRT resolves them when it loads the library.
    readelf = subprocess.run(["readelf", "-d", str(plugin_file)], capture_output=True, text=True).stdout
    needed = [line.split("[")[1].rstrip("]") for line in readelf.splitlines() if "(NEEDED)" in line]
    assert not any("python" in n or "triton" in n for n in needed), f"unexpected dependency in {needed}"
    print(f"    {plugin_file.name} NEEDED: {', '.join(needed)}")
    return

@case_mark
def case_generated_plugin_with_tactics():
    """`plugin_gen.py` writes the plugin for a different operator, and the AOT variants become tactics.

    GELU, no attribute, three `BLOCK_SIZE` / `num_warps` combinations compiled ahead of time and
    linked into one dispatcher. TensorRT times all three during the build and bakes the winner into
    the engine, which is Triton autotuning moved to build time.
    """
    generated_plugin_file = plugin_gen.generate(plugin_gen.GELU_SPEC)

    plugin_info = dict(
        name="GeluTriton",
        version="1",
        namespace="",
        argument_dict=dict(),
        number_input_tensor=1,
        number_input_shape_tensor=0,
        plugin_api_version="3",
    )
    output, tw = build_and_run([generated_plugin_file], plugin_info, Path("model-generated.trt"), "GeluTritonLayer")

    x = input_data["inputT0"]
    reference = x * 0.5 * (1.0 + erf(x / np.sqrt(2.0)))
    check_array(output, reference, True)

    variant_list = plugin_gen.GELU_SPEC["variant_list"]

    # Which specialization did the builder keep? On TensorRT 11.1.0.106 you cannot tell from the
    # engine information, even at DETAILED verbosity: the plugin is absorbed into Myelin and comes
    # back as a `custom_layer` named `<layer name>_myl0_*`, with no `PluginType` and no
    # `TacticValue` key at all, and an empty `TacticName`. Same result for a static-shape build, so
    # it is not a side effect of the dynamic profile. Print what is actually there rather than
    # indexing a key that no longer exists.
    information = json.loads(tw.engine.create_engine_inspector().get_engine_information(trt.LayerInformationFormat.JSON))
    plugin_layer_list = [layer for layer in information["Layers"] if "GeluTritonLayer" in layer["Name"]]
    for layer in plugin_layer_list:
        keys = ", ".join(f"{k}={layer.get(k)!r}" for k in ("LayerType", "PluginType", "TacticValue", "TacticName") if k in layer)
        print(f"    engine information for {layer['Name']}: {keys}")
    if not any("TacticValue" in layer for layer in plugin_layer_list):
        print(f"    -> the {len(variant_list)} AOT variants are still tactics, but which one won is NOT observable here")
        print(f"       (no `TacticValue`/`PluginType` on a Myelin-absorbed plugin; measure instead of reading a field)")

    # So measure it. Rebuild with only the first variant available and compare: if the builder were
    # not really timing the variants, these two engines would run at the same speed.
    single_spec = dict(plugin_gen.GELU_SPEC, plugin_name="GeluTritonSingle", variant_list=variant_list[:1])
    single_plugin_file = plugin_gen.generate(single_spec, b_verbose=False)
    _, tw_single = build_and_run([single_plugin_file], dict(plugin_info, name="GeluTritonSingle"), None, "GeluTritonSingleLayer")

    time_dict = {}
    for tag, wrapper in [("all tactics", tw), ("only variant 1", tw_single)]:
        for _ in range(20):
            wrapper.context.execute_async_v3(0)
        cudart.cudaDeviceSynchronize()
        start_time = time.perf_counter()
        for _ in range(200):
            wrapper.context.execute_async_v3(0)
        cudart.cudaDeviceSynchronize()
        time_dict[tag] = (time.perf_counter() - start_time) * 1000 / 200
        print(f"    {tag:15s}: {time_dict[tag]:.4f} ms")
    speedup = time_dict["only variant 1"] / time_dict["all tactics"]
    print(f"    -> letting the builder choose is {speedup:.2f}x the fixed first variant")
    assert speedup > 1.2, f"expected the tactic search to pay off, got {speedup:.2f}x -- did all variants collapse to one?"
    return

if __name__ == "__main__":
    for trt_path in Path(".").glob("*.trt"):
        trt_path.unlink(missing_ok=True)

    case_hand_written_plugin()
    case_the_fp32_argument_trap()
    case_no_python_no_triton_at_runtime()
    case_generated_plugin_with_tactics()

    print("\nFinish")
