# Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Write a TensorRT plugin from a Triton kernel plus a small spec.

The hand-written `AddScalarTritonPlugin.cu` is ~330 lines of which about six are about the kernel;
everything else follows mechanically from "one input, one output, same shape, FP32, elementwise".
That is what this file automates, and it is the reason a generator is worth having: the boilerplate
is not just long, it is the part that goes wrong silently (a missing `setLoggerFinder`, a forgotten
`double` -> `float` patch).

The generator also does something the hand-written plugin cannot do conveniently: it AOT-compiles
the **same kernel several times** with different `BLOCK_SIZE` / `num_warps`, links them into one
dispatcher, and exposes each specialization as a TensorRT **tactic**. TensorRT then times them
during the build and bakes the winner into the engine -- Triton autotuning done by the TensorRT
builder, with no autotuner at run time.

Scope, stated honestly: this handles element-wise kernels shaped
`kernel(in0_ptr, ..., out_ptr, <float attributes>, n_element, BLOCK_SIZE: constexpr)` over FP32.
That is enough for both operators here and small enough to read; anything else (multiple outputs,
shape changes, other dtypes) needs the spec and the templates extended.
"""

import re
import shutil
import subprocess
from pathlib import Path

current_path = Path(__file__).parent

HEADER_TEMPLATE = """/*
 * SPDX-License-Identifier: Apache-2.0
 * GENERATED by plugin_gen.py from {kernel_name} in {kernel_file} -- do not edit.
 */

#include "cookbookHelper.cuh"

namespace
{{
inline constexpr char PLUGIN_NAME[] {{"{plugin_name}"}};
inline constexpr char PLUGIN_NAMESPACE[] {{""}};
inline constexpr char PLUGIN_VERSION[] {{"1"}};
inline constexpr int32_t N_TACTIC {{{n_tactic}}};
}} // namespace

namespace nvinfer1
{{
class {class_name} : public IPluginV3, public IPluginV3OneCore, public IPluginV3OneBuild, public IPluginV3OneRuntime
{{
private:
{member_declaration}    int32_t                  mTactic {{1}};
    std::vector<PluginField> mDataToSerialize;
    PluginFieldCollection    mFCToSerialize;

public:
    {class_name}({constructor_parameter});
    {class_name}({class_name} const &p) = default;

    IPluginCapability *getCapabilityInterface(PluginCapabilityType type) noexcept override;
    IPluginV3         *clone() noexcept override;
    char const *getPluginName() const noexcept override;
    char const *getPluginVersion() const noexcept override;
    char const *getPluginNamespace() const noexcept override;
    int32_t     configurePlugin(DynamicPluginTensorDesc const *in, int32_t nbInputs, DynamicPluginTensorDesc const *out, int32_t nbOutputs) noexcept override;
    int32_t     getOutputDataTypes(DataType *outputTypes, int32_t nbOutputs, DataType const *inputTypes, int32_t nbInputs) const noexcept override;
    int32_t     getOutputShapes(DimsExprs const *inputs, int32_t nbInputs, DimsExprs const *shapeInputs, int32_t nbShapeInputs, DimsExprs *outputs, int32_t nbOutputs, IExprBuilder &exprBuilder) noexcept override;
    bool        supportsFormatCombination(int32_t pos, DynamicPluginTensorDesc const *inOut, int32_t nbInputs, int32_t nbOutputs) noexcept override;
    int32_t     getNbOutputs() const noexcept override;
    size_t      getWorkspaceSize(DynamicPluginTensorDesc const *inputs, int32_t nbInputs, DynamicPluginTensorDesc const *outputs, int32_t nbOutputs) const noexcept override;
    int32_t     getValidTactics(int32_t *tactics, int32_t nbTactics) noexcept override;
    int32_t     getNbTactics() noexcept override;
    char const *getTimingCacheID() noexcept override;
    int32_t     getFormatCombinationLimit() noexcept override;
    char const *getMetadataString() noexcept override;
    int32_t                      setTactic(int32_t tactic) noexcept override;
    int32_t                      onShapeChange(PluginTensorDesc const *in, int32_t nbInputs, PluginTensorDesc const *out, int32_t nbOutputs) noexcept override;
    int32_t                      enqueue(PluginTensorDesc const *inputDesc, PluginTensorDesc const *outputDesc, void const *const *inputs, void *const *outputs, void *workspace, cudaStream_t stream) noexcept override;
    IPluginV3                   *attachToContext(IPluginResourceContext *context) noexcept override;
    PluginFieldCollection const *getFieldsToSerialize() noexcept override;
}};

class {class_name}Creator : public IPluginCreatorV3One
{{
private:
    PluginFieldCollection    mFC;
    std::vector<PluginField> mPluginAttributes;

public:
    {class_name}Creator();
    char const                  *getPluginName() const noexcept override;
    char const                  *getPluginVersion() const noexcept override;
    PluginFieldCollection const *getFieldNames() noexcept override;
    IPluginV3                   *createPlugin(char const *name, PluginFieldCollection const *fc, TensorRTPhase phase) noexcept override;
    char const                  *getPluginNamespace() const noexcept override;
}};

}} // namespace nvinfer1
"""

SOURCE_TEMPLATE = """/*
 * SPDX-License-Identifier: Apache-2.0
 * GENERATED by plugin_gen.py from {kernel_name} in {kernel_file} -- do not edit.
 * AOT variants (tactic = index + 1): {variant_comment}
 */

#include "{plugin_name}Plugin.h"

#include <cstdint>
#include <cstring>
#include <cuda.h>
#include <limits>
#include <memory>

extern "C"
{{
#include "{stem}.h"
}}

// Required together with getCreators, otherwise the creators are silently never registered
extern "C" void setLoggerFinder(nvinfer1::ILoggerFinder *finder) {{}}

namespace nvinfer1
{{

{class_name}::{class_name}({constructor_parameter}){constructor_initializer}
{{
}}

IPluginCapability *{class_name}::getCapabilityInterface(PluginCapabilityType type) noexcept
{{
    switch (type)
    {{
    case PluginCapabilityType::kBUILD:
        return static_cast<IPluginV3OneBuild *>(this);
    case PluginCapabilityType::kRUNTIME:
        return static_cast<IPluginV3OneRuntime *>(this);
    case PluginCapabilityType::kCORE:
        return static_cast<IPluginV3OneCore *>(this);
    }}
    return nullptr;
}}

IPluginV3 *{class_name}::clone() noexcept
{{
    try
    {{
        std::unique_ptr<{class_name}> p {{std::make_unique<{class_name}>(*this)}};
        return p.release();
    }}
    catch (...)
    {{
        return nullptr;
    }}
}}

char const *{class_name}::getPluginName() const noexcept
{{
    return PLUGIN_NAME;
}}

char const *{class_name}::getPluginVersion() const noexcept
{{
    return PLUGIN_VERSION;
}}

char const *{class_name}::getPluginNamespace() const noexcept
{{
    return PLUGIN_NAMESPACE;
}}

int32_t {class_name}::configurePlugin(DynamicPluginTensorDesc const *in, int32_t nbInputs, DynamicPluginTensorDesc const *out, int32_t nbOutputs) noexcept
{{
    return (in != nullptr && out != nullptr && nbInputs == {n_input} && nbOutputs == 1) ? 0 : -1;
}}

int32_t {class_name}::getOutputDataTypes(DataType *outputTypes, int32_t nbOutputs, DataType const *inputTypes, int32_t nbInputs) const noexcept
{{
    if (outputTypes == nullptr || inputTypes == nullptr || nbInputs != {n_input} || nbOutputs != 1)
    {{
        return -1;
    }}
    outputTypes[0] = inputTypes[0];
    return 0;
}}

int32_t {class_name}::getOutputShapes(DimsExprs const *inputs, int32_t nbInputs, DimsExprs const *shapeInputs, int32_t nbShapeInputs, DimsExprs *outputs, int32_t nbOutputs, IExprBuilder &exprBuilder) noexcept
{{
    if (inputs == nullptr || outputs == nullptr || nbInputs != {n_input} || nbOutputs != 1)
    {{
        return -1;
    }}
    outputs[0].nbDims = inputs[0].nbDims;
    for (int32_t i = 0; i < outputs[0].nbDims; ++i)
    {{
        outputs[0].d[i] = inputs[0].d[i];
    }}
    return 0;
}}

bool {class_name}::supportsFormatCombination(int32_t pos, DynamicPluginTensorDesc const *inOut, int32_t nbInputs, int32_t nbOutputs) noexcept
{{
    if (inOut == nullptr || nbInputs != {n_input} || nbOutputs != 1 || pos < 0 || pos >= nbInputs + nbOutputs)
    {{
        return false;
    }}
    // The kernel was AOT-compiled for *fp32 only
    if (pos == 0)
    {{
        return inOut[0].desc.type == DataType::kFLOAT && inOut[0].desc.format == TensorFormat::kLINEAR;
    }}
    return inOut[pos].desc.type == inOut[0].desc.type && inOut[pos].desc.format == inOut[0].desc.format;
}}

int32_t {class_name}::getNbOutputs() const noexcept
{{
    return 1;
}}

size_t {class_name}::getWorkspaceSize(DynamicPluginTensorDesc const *inputs, int32_t nbInputs, DynamicPluginTensorDesc const *outputs, int32_t nbOutputs) const noexcept
{{
    return 0;
}}

int32_t {class_name}::getValidTactics(int32_t *tactics, int32_t nbTactics) noexcept
{{
    // One tactic per AOT specialization. Custom tactic values must be positive, so tactic == algo_id + 1.
    if (tactics == nullptr || nbTactics != N_TACTIC)
    {{
        return -1;
    }}
    for (int32_t i = 0; i < N_TACTIC; ++i)
    {{
        tactics[i] = i + 1;
    }}
    return 0;
}}

int32_t {class_name}::getNbTactics() noexcept
{{
    return N_TACTIC;
}}

char const *{class_name}::getTimingCacheID() noexcept
{{
    return "_{plugin_name}Plugin";
}}

int32_t {class_name}::getFormatCombinationLimit() noexcept
{{
    return 0;
}}

char const *{class_name}::getMetadataString() noexcept
{{
    return nullptr;
}}

int32_t {class_name}::setTactic(int32_t tactic) noexcept
{{
    // TensorRT passes 0 to mean "the default tactic" when it is not timing a specific one
    mTactic = (tactic == 0) ? 1 : tactic;
    return (mTactic >= 1 && mTactic <= N_TACTIC) ? 0 : -1;
}}

int32_t {class_name}::onShapeChange(PluginTensorDesc const *in, int32_t nbInputs, PluginTensorDesc const *out, int32_t nbOutputs) noexcept
{{
    return (in != nullptr && out != nullptr && nbInputs == {n_input} && nbOutputs == 1) ? 0 : -1;
}}

int32_t {class_name}::enqueue(PluginTensorDesc const *inputDesc, PluginTensorDesc const *outputDesc, void const *const *inputs, void *const *outputs, void *workspace, cudaStream_t stream) noexcept
{{
    if (inputDesc == nullptr || inputs == nullptr || outputs == nullptr || outputs[0] == nullptr)
    {{
        return -1;
    }}

    int64_t nElement64 {{1}};
    for (int32_t i = 0; i < inputDesc[0].dims.nbDims; ++i)
    {{
        int32_t const dim = inputDesc[0].dims.d[i];
        nElement64 *= dim;
        if (dim <= 0 || nElement64 > std::numeric_limits<int32_t>::max())
        {{
            return -1;
        }}
    }}

    CUresult const ret = {stem}({call_argument}, mTactic - 1);
    if (ret != CUDA_SUCCESS)
    {{
        return -1;
    }}
    return (cudaGetLastError() == cudaSuccess) ? 0 : -1;
}}

IPluginV3 *{class_name}::attachToContext(IPluginResourceContext *context) noexcept
{{
    try
    {{
        load_{stem}(); // Bind the cubin to the context TensorRT is going to run in
        return clone();
    }}
    catch (...)
    {{
        return nullptr;
    }}
}}

PluginFieldCollection const *{class_name}::getFieldsToSerialize() noexcept
{{
    try
    {{
        mDataToSerialize.clear();
{serialize_body}        mFCToSerialize.nbFields = mDataToSerialize.size();
        mFCToSerialize.fields   = mDataToSerialize.data();
        return &mFCToSerialize;
    }}
    catch (...)
    {{
        return nullptr;
    }}
}}

{class_name}Creator::{class_name}Creator()
{{
    mPluginAttributes.clear();
{attribute_body}    mFC.nbFields = mPluginAttributes.size();
    mFC.fields   = mPluginAttributes.data();
}}

char const *{class_name}Creator::getPluginName() const noexcept
{{
    return PLUGIN_NAME;
}}

char const *{class_name}Creator::getPluginVersion() const noexcept
{{
    return PLUGIN_VERSION;
}}

PluginFieldCollection const *{class_name}Creator::getFieldNames() noexcept
{{
    return &mFC;
}}

IPluginV3 *{class_name}Creator::createPlugin(char const *name, PluginFieldCollection const *fc, TensorRTPhase phase) noexcept
{{
    try
    {{
{parse_body}        return new {class_name}({constructor_argument});
    }}
    catch (...)
    {{
        return nullptr;
    }}
}}

char const *{class_name}Creator::getPluginNamespace() const noexcept
{{
    return PLUGIN_NAMESPACE;
}}

}} // namespace nvinfer1

extern "C" nvinfer1::IPluginCreatorV3One *const *getCreators(int32_t &nbCreators)
{{
    nbCreators = 1;
    static nvinfer1::{class_name}Creator      creator;
    static nvinfer1::IPluginCreatorV3One *const pluginCreatorList[] = {{&creator}};
    return pluginCreatorList;
}}
"""

MAKEFILE_TEMPLATE = """TRT_COOKBOOK_PATH ?= {cookbook_path}
include $(TRT_COOKBOOK_PATH)/include/Makefile.inc
LDFLAG += -lcuda

# GENERATED by plugin_gen.py -- do not edit.
all: {plugin_name}Plugin.so

{plugin_name}Plugin.o: {plugin_name}Plugin.cu {plugin_name}Plugin.h {stem}.h
\t$(COMMAND_O)

{stem}.o: {stem}.c
\t$(NVCC) -x c -O3 -Xcompiler -fPIC -I$(CUDA_PATH)/include -o $@ -c $<

{variant_object_rule}
{plugin_name}Plugin.so: {plugin_name}Plugin.o cookbookHelper.o {stem}.o {variant_object}
\t$(COMMAND_SO)
"""

def compile_kernel_variants(spec, output_path: Path):
    """Run `triton.tools.compile` once per variant, link them, and patch the fp32 ABI bug.

    Returns the list of per-variant `.c` files, in the order the linker will see them -- that order
    is the `algo_id` order, hence the tactic order.
    """
    stem = spec["stem"]
    header_list = []
    for variant in spec["variant_list"]:
        command = [
            "python3",
            "-m",
            "triton.tools.compile",
            str(current_path / spec["kernel_file"]),
            "--kernel-name",
            spec["kernel_name"],
            "--out-name",
            stem,
            "-o",
            str(output_path / stem),
            "--num-warps",
            str(variant["num_warps"]),
            "--signature",
            spec["signature"].format(**variant),
            "--grid",
            spec["grid"].format(**variant),
        ]
        subprocess.run(command, check=True, capture_output=True)
    # `link` sorts by the header names it is given; sort them so the tactic order is reproducible
    header_list = sorted(output_path.glob(f"{stem}.*.h"))
    subprocess.run(["python3", "-m", "triton.tools.link", *[str(p) for p in header_list], "-o", str(output_path / stem)], check=True, capture_output=True)

    # The fp32 ABI patch, applied to every generated file. `triton.tools.compile` declares an `fp32`
    # kernel argument as `double` in C and then hands `&arg` to `cuLaunchKernel`, whose parameter
    # slot is 4 bytes wide -> the kernel reads the low half of the double. See README.md.
    for attribute in spec["attribute_list"]:
        for path in list(output_path.glob(f"{stem}*.c")) + list(output_path.glob(f"{stem}*.h")):
            path.write_text(re.sub(rf"\bdouble {attribute}\b", f"float {attribute}", path.read_text()))
    return sorted(output_path.glob(f"{stem}.*.c"))

def generate(spec, b_verbose: bool = True) -> Path:
    """Emit, compile and link a complete plugin. Returns the path of the `.so`."""
    # One directory per plugin: two generated plugins must be able to coexist, and wiping a shared
    # directory would delete a `.so` TensorRT still has open.
    output_path = current_path / "generated" / spec["plugin_name"]
    shutil.rmtree(output_path, ignore_errors=True)
    output_path.mkdir(parents=True, exist_ok=True)

    variant_source_list = compile_kernel_variants(spec, output_path)
    assert len(variant_source_list) == len(spec["variant_list"]), \
        f"{len(spec['variant_list'])} variants asked for but {len(variant_source_list)} compiled: two variants collided into one cubin"

    plugin_name = spec["plugin_name"]
    attribute_list = spec["attribute_list"]
    substitution = dict(
        plugin_name=plugin_name,
        class_name=f"{plugin_name}Plugin",
        stem=spec["stem"],
        kernel_name=spec["kernel_name"],
        kernel_file=spec["kernel_file"],
        n_input=spec["n_input"],
        n_tactic=len(spec["variant_list"]),
        variant_comment=", ".join(f"BLOCK_SIZE={v['block_size']}/num_warps={v['num_warps']}" for v in spec["variant_list"]),
        member_declaration="".join(f"    float                    m_{a} {{0.0f}};\n" for a in attribute_list),
        constructor_parameter=", ".join(f"float const {a}" for a in attribute_list) if attribute_list else "",
        constructor_initializer=(":\n    " + ", ".join(f"m_{a}({a})" for a in attribute_list)) if attribute_list else "",
        constructor_argument=", ".join(attribute_list),
        call_argument=", ".join(["stream"] + [f"reinterpret_cast<CUdeviceptr>(inputs[{i}])" for i in range(spec["n_input"])] + ["reinterpret_cast<CUdeviceptr>(outputs[0])"] + [f"m_{a}" for a in attribute_list] + ["static_cast<int32_t>(nElement64)"]),
        serialize_body="".join(f'        mDataToSerialize.emplace_back(PluginField("{a}", &m_{a}, PluginFieldType::kFLOAT32, 1));\n' for a in attribute_list),
        attribute_body="".join(f'    mPluginAttributes.emplace_back(PluginField("{a}", nullptr, PluginFieldType::kFLOAT32, 1));\n' for a in attribute_list),
        parse_body="".join(f"""        float {a} {{0.f}};
        for (int32_t i = 0; fc != nullptr && fc->fields != nullptr && i < fc->nbFields; ++i)
        {{
            if (fc->fields[i].name != nullptr && std::strcmp(fc->fields[i].name, "{a}") == 0 && fc->fields[i].data != nullptr)
            {{
                {a} = *static_cast<float const *>(fc->fields[i].data);
            }}
        }}
""" for a in attribute_list),
    )

    (output_path / f"{plugin_name}Plugin.h").write_text(HEADER_TEMPLATE.format(**substitution))
    (output_path / f"{plugin_name}Plugin.cu").write_text(SOURCE_TEMPLATE.format(**substitution))
    variant_object = " ".join(p.with_suffix(".o").name for p in variant_source_list)
    (output_path / "Makefile").write_text(MAKEFILE_TEMPLATE.format(
        cookbook_path=current_path.parent.parent,
        plugin_name=plugin_name,
        stem=spec["stem"],
        variant_object=variant_object,
        variant_object_rule="\n".join(f"{p.with_suffix('.o').name}: {p.name}\n\t$(NVCC) -x c -O3 -Xcompiler -fPIC -I$(CUDA_PATH)/include -o $@ -c $<\n" for p in variant_source_list),
    ))

    subprocess.run(["make", "all", "-j"], cwd=output_path, check=True, capture_output=True)
    if b_verbose:
        line_count = sum(len((output_path / f"{plugin_name}Plugin{suffix}").read_text().splitlines()) for suffix in [".h", ".cu"])
        print(f"    generated {line_count} lines of C++ for {plugin_name} from a {len(spec)}-key spec, "
              f"{len(spec['variant_list'])} AOT variants -> {len(spec['variant_list'])} TensorRT tactics")
    return output_path / f"{plugin_name}Plugin.so"

# The spec for a second, different operator: no attribute, different argument list, three variants.
GELU_SPEC = dict(
    plugin_name="GeluTriton",
    kernel_file="kernel.py",
    kernel_name="gelu_kernel",
    stem="gelu",
    n_input=1,
    attribute_list=[],
    signature="*fp32:16, *fp32:16, i32, {block_size}",
    grid="(n_element + {block_size} - 1) / {block_size}, 1, 1",
    variant_list=[
        dict(block_size=128, num_warps=1),
        dict(block_size=1024, num_warps=4),
        dict(block_size=4096, num_warps=8),
    ],
)

if __name__ == "__main__":
    print(generate(GELU_SPEC))
