# Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Dumping a parsed TensorRT network as an ONNX-like file, to look at it in Netron.

`OnnxLikeFromNetwork` walks an `INetworkDefinition` and writes an ONNX file whose
nodes are named after **TensorRT layer types** (`CONVOLUTION`, `SHUFFLE`, ...).
It is explicitly not valid ONNX -- `onnx.checker` rejects it. The point is to see
what the parser actually produced, which is often not what the source ONNX
looked like.

The cookbook has its own version of this, `export_network_as_onnx` in
`tensorrt_cookbook`, used by `08-Advance/Subgraph/`. `case_compare_the_two_tools`
runs both on the same network, and they do not agree on what is exportable.
"""

from collections import Counter
from pathlib import Path

import onnx
from polygraphy.backend.trt import NetworkFromOnnxPath, onnx_like_from_network
from polygraphy.logger import G_LOGGER

from tensorrt_cookbook import case_mark, cookbook_path, export_network_as_onnx

G_LOGGER.module_severity = G_LOGGER.ERROR

output_path = Path(__file__).parent
mnist_onnx = str(cookbook_path("00-Data", "model", "model-trained.onnx"))
# The `Loop` whose body holds an `If`, from `08-Advance/Subgraph/`. Generated by
# that example; regenerate with `python3 08-Advance/Subgraph/main.py` if missing.
subgraph_onnx = cookbook_path("08-Advance", "Subgraph") / "example.onnx"

def describe(model, tag: str) -> None:
    """Node count, op-type histogram and how many nodes still carry a sub-graph."""
    n_subgraph = sum(1 for node in model.graph.node for attribute in node.attribute if attribute.type in (onnx.AttributeProto.GRAPH, onnx.AttributeProto.GRAPHS))
    print(f"    {tag}: {len(model.graph.node)} nodes, {n_subgraph} with a sub-graph, {len(model.graph.initializer)} initializers")
    print(f"      op types: {dict(Counter(node.op_type for node in model.graph.node))}")
    return

@case_mark
def case_what_the_parser_produced() -> None:
    """The source ONNX against the network TensorRT built from it.

    12 ONNX nodes become 27 TensorRT layers: the parser inserts shuffles, casts
    and constants that are nowhere in the original file. That expansion is the
    reason to dump the network rather than read the ONNX.
    """
    source = onnx.load(mnist_onnx)
    describe(source, "source ONNX      ")

    network_like = onnx_like_from_network(NetworkFromOnnxPath(mnist_onnx))
    describe(network_like, "TensorRT network")

    export_file = output_path / "mnist-network.onnx"
    onnx.save(network_like, str(export_file))
    print(f"    saved {export_file.name} for Netron")
    return

@case_mark
def case_it_is_not_valid_onnx() -> None:
    """The file uses the ONNX container with node types ONNX has never heard of.

    This is stated in the API docstring (`[HIGHLY EXPERIMENTAL] ... not valid
    ONNX`) and worth seeing, because the file opens fine in Netron and looks
    entirely legitimate until something tries to load it as a model.

    The size is the second surprise. There are zero initializers, which looks
    like the weights were dropped -- they were not. Every TensorRT layer
    parameter becomes an ONNX *attribute*, weights included, so a convolution
    carries its whole kernel as a `FLOATS` list. Protobuf stores those far less
    compactly than an initializer's packed `raw_data`, and the dump comes out
    bigger than the model it was made from.
    """
    network_like = onnx_like_from_network(NetworkFromOnnxPath(mnist_onnx))
    try:
        onnx.checker.check_model(network_like)
        print("    onnx.checker: unexpectedly passed")
    except Exception as e:
        print(f"    onnx.checker: {type(e).__name__}: {str(e).splitlines()[0][:78]}")

    convolution = next(node for node in network_like.graph.node if node.op_type == "CONVOLUTION")
    attribute = {a.name: len(onnx.helper.get_attribute_value(a)) for a in convolution.attribute if a.type in (onnx.AttributeProto.FLOATS, onnx.AttributeProto.INTS)}
    print(f"    initializers: {len(network_like.graph.initializer)} -- but the weights are still there, as attributes:")
    print(f"      first CONVOLUTION: kernel={attribute['kernel']} floats, bias={attribute['bias']} floats, plus stride/padding/dilation")
    print(f"    so the dump is {(output_path / 'mnist-network.onnx').stat().st_size / 1024 ** 2:.1f} MB against a {Path(mnist_onnx).stat().st_size / 1024 ** 2:.1f} MB source model")
    print("    for visualisation and debugging only; it will not run anywhere")
    return

@case_mark
def case_compare_the_two_tools() -> None:
    """Polygraphy's exporter against the cookbook's, on a control-flow network.

    `08-Advance/Subgraph/` parses an ONNX whose main graph holds a `Loop` whose
    body holds an `If`. TensorRT flattens both into one layer list, and the
    cookbook's `export_network_as_onnx` dumps that list happily.

    Polygraphy's `OnnxLikeFromNetwork` does not: it raises while converting the
    loop and conditional boundary layers' attributes. Same network, same goal,
    different outcome -- worth knowing before reaching for either.
    """
    if not subgraph_onnx.exists():
        print(f"    skipped: {subgraph_onnx} not found, run 08-Advance/Subgraph/main.py first")
        return

    source = onnx.load(str(subgraph_onnx))
    n_subgraph = sum(1 for node in source.graph.node for attribute in node.attribute if attribute.type in (onnx.AttributeProto.GRAPH, onnx.AttributeProto.GRAPHS))
    print(f"    source ONNX: {len(source.graph.node)} nodes, {n_subgraph} of them hold a sub-graph")

    try:
        network_like = onnx_like_from_network(NetworkFromOnnxPath(str(subgraph_onnx)))
        describe(network_like, "polygraphy OnnxLikeFromNetwork")
    except Exception as e:
        print(f"    polygraphy OnnxLikeFromNetwork : {type(e).__name__}: {str(e).splitlines()[0][:72]}")

    import tensorrt as trt
    builder = trt.Builder(trt.Logger(trt.Logger.ERROR))
    network = builder.create_network()
    parser = trt.OnnxParser(network, trt.Logger(trt.Logger.ERROR))
    parser.parse_from_file(str(subgraph_onnx))
    export_file = output_path / "subgraph-network.onnx"
    export_network_as_onnx(network, export_file)
    print(f"    cookbook  export_network_as_onnx: {len(onnx.load(str(export_file)).graph.node)} nodes written")
    print("    the cookbook helper handles the loop/conditional boundary layers; Polygraphy's does not")
    return

if __name__ == "__main__":
    case_what_the_parser_produced()
    case_it_is_not_valid_onnx()
    case_compare_the_two_tools()

    print("\nFinish")
