repos:
#-   repo: https://github.com/pycqa/isort  # no always running this since it has confilct with yapf
#    rev: 5.12.0
#    hooks:
#    -   id: isort
#        verbose: true
-   repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.1.13
    hooks:
    -   id: remove-crlf
-   repo: https://github.com/google/yapf
    rev: v0.32.0
    hooks:
    -   id: yapf
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/autoflake
    rev: v1.6.1
    hooks:
    -   id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variables']
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.0
    hooks:
    -   id: clang-format
        types_or: [c++, c, cuda]
        # exclude /07-Tool/NetworkInspector/C++/json.hpp
        exclude: |
            (?x)^.*json.hpp$
-   repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.10
    hooks:
    -   id: cmake-format
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
    -   id: codespell
        args:
        - --skip=".git,3rdparty,*.ipynb,*.txt"
        - --ignore-words-list=ot,wih,woh,padd,inout,nd,ned  # low-case here!
        exclude: '07-Tool/'
