# Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from tensorrt_cookbook import build_readme, cookbook_path

# The cookbook root's outline lives here rather than in a `README.outline.txt` sitting beside the
# `README.md` it generates, where the two were easy to mistake for each other. Every sub-directory
# still keeps its own `README.outline.txt`, since those belong next to the content they introduce.
#
# A raw string: the outline contains shell line continuations, and in a normal string a trailing
# backslash would splice the lines together and quietly break the `docker run` block.
ROOT_OUTLINE = r"""
+ **This README.md is generated by `build-Copyright-and-README.py`; edit `ROOT_OUTLINE` in that script, not this file.**

<p align="center">
<img src="TensorRTCookbook-ico.png" width="200px" height="200px" alt="description">
</p>

+ This repository is presented for NVIDIA TensorRT beginners and developers, which provides TensorRT-related learning and reference materials, as well as code examples.

+ Recommend order to read the subtopics if you are a freshman to the TensorRT:
  + 01-SimpleDemo/TensorRT10
  + 03-Workflow/pyTorch-ONNX-TensorRT
  + 07-Tool/Netron
  + 07-Tool/trtexec
  + 05-Plugin/BasicExample
  + 05-Plugin/ONNXParserWithPlugin
  + ...

## Steps to setup

+ We recommend to use NVIDIA-optimized Docker to run the examples: [Steps to install](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker)
+ The information of the docker images can be found from [here](https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html)
+ The packages of pyTorch and TensorFlow in the Docker is somewhere different from the version installed directly by `pip install`, especially quantization related features. So I recommend you use them inside the docker image rather than install by yourself.
+ Recommended docker images

|            Name of Docker Image             | python |  Driver   |    CUDA    |  TensorRT  | Nsight-Systems |            Comment             |
| :-----------------------------------------: | :----: | :-------: | :--------: | :--------: | :------------: | :----------------------------: |
|    **nvcr.io/nvidia/tensorrt:19.12-py3**    |  3.6   | 440.33.01 |  10.2.89   |   6.0.1    |    2019.6.1    |  Last version with TensorRT 6  |
|    **nvcr.io/nvidia/tensorrt:21.06-py3**    |  3.8   | 465.19.01 |   11.3.1   |  7.2.3.4   |  2021.2.1.58   |  Last version with TensorRT 7  |
|    **nvcr.io/nvidia/pytorch:23.02-py3**     |  3.8   |    525    |   12.0.1   |   8.5.3    |    2022.5.1    |  Last version with pyTorch 1   |
| **nvcr.io/nvidia/tensorflow:23.03-tf1-py3** |  3.8   |    530    |   12.1.0   |   8.5.3    |  2023.1.1.127  | Last version with TensorFlow 1 |
|    **nvcr.io/nvidia/pytorch:24.04-py3**     |  3.10  |    545    |   12.3.2   |  8.6.1.6   |  2023.4.1.97   |  Last version with TensorRT 8  |
|    **nvcr.io/nvidia/pytorch:25.06-py3**     |  3.12  |     /     | 12.9.1.010 | 10.11.0.33 |  2025.5.1.121  |   Last version with CUDA 12    |
|    **nvcr.io/nvidia/pytorch:26.05-py3**     |  3.12  |     /     |   13.2.1   | 10.16.1.11 |  2026.2.1.210  | Last version with TensorRT 10  |
|    **nvcr.io/nvidia/pytorch:26.06-py3**     |  3.12  |     /     |   13.3.0   | 11.0.0.114 |       ?        |       **prefer version**       |

+ Start the container

```bash
docker run \
    -it -e NVIDIA_VISIBLE_DEVICES=0 --gpus "device=0" \
    --shm-size 16G --ulimit memlock=-1 --ulimit stack=67108864 \
    --name trt-cookbook \
    -v <PathToTheCookbookRepo>:/trtcookbook \
    nvcr.io/nvidia/pytorch:26.03-py3 \
    /bin/bash
```

+ Inside the container

```bash
cd <PathToTheCookbookRepo>
export TRT_COOKBOOK_PATH=$(pwd)  # Optional: package now auto-discovers this path in most cases.
pip install -r requirements.txt  # Add "-i https://pypi.tuna.tsinghua.edu.cn/simple" to accelerate downloading for Chinese users.

# For release usage:
python -m pip install -U build
rm -rf build dist
python -m build
apt-get update && apt-get install -y graphviz git-lfs
pip install dist/*.whl

# For developer usage:
apt-get update && apt-get install -y graphviz git-lfs
pip install -e . --no-deps
```

+ [Optional] Prepare the dataset (following the steps in 00-Data/README.md) which some examples need.

+ Now it's OK to go through other directories and enjoy the examples.

+ Related materials (slices, datasets, models and PDF files): [Baidu Netdisk](https://pan.baidu.com/s/14HNCFbySLXndumicFPD-Ww?pwd=gpq2).

+ Related video tutorial on Bilibili website:
  + [TensorRT-8.6.1](https://www.bilibili.com/video/BV1jj411Z7wG/)
  + [TensorRT-8.2.3](https://www.bilibili.com/video/BV15Y4y1W73E)
  + [Hackathon2022](https://www.bilibili.com/video/BV1i3411G7vN)
  + [Hackathon2023](https://www.bilibili.com/video/BV1dw411r7X8/)

## Important update of the repository

+ **1st April 2026**. Release of tensorrt-cookbook v1.0.0-trt-10.16. Update to TensorRT 10.16.

+ **20th November 2025**. Update to TensorRT 10.13, APIs of `cuda-python` change in new version.

+ **18th June 2025**. Update to TensorRT 10.12, much stuff is deprecated.

+ **1st November 2024**. Update to TensorRT 10.6, package `tensorrt_cookbook.whl` for installation.

+ **20th September 2024**. Update to TensorRT 10.5.

+ **1st May 2024**. Update to TensorRT 10.0 GA.
  + From branch TensorRT-10.0, we will discard several examples in older TensorRT versions.

+ **12th February 2024**. Update to TensorRT 9.X GA.

+ **18th June 2023**. Update to TensorRT 8.6 GA. Finish TensorRT tutorial (slice + audio) for Bilibili.

+ **17th March 2023**. Freeze code of branch TensorRT-8.5
  + Translate almost all contents into English.
  + Come to development work of TensorRT 8.6 EA

+ **10th October 2022**. Update to TensorRT 8.5 GA. Cookbook with TensorRT 8.4 is remained in branch old/TensorRT-8.4.

+ **15th July 2022**. Update to TensorRT 8.4 GA. Cookbook with older version of TensorRT is remained in branch old/TensorRT-8.2.

## Useful Links

+ [Git address of this repo](https://github.com/wili-65535/trt-samples-for-hackathon-cn.git)
+ [**TensorRT Download**](https://developer.nvidia.com/tensorrt/download)
+ [NVIDIA/TensorRT](https://github.com/NVIDIA/TensorRT)
+ [Document](https://docs.nvidia.com/deeplearning/tensorrt/)
+ [C++ API](https://docs.nvidia.com/deeplearning/tensorrt/latest/_static/c-api/index.html)
+ [Python API](https://docs.nvidia.com/deeplearning/tensorrt/latest/_static/python-api/index.html)
+ [Operators Document](https://docs.nvidia.com/deeplearning/tensorrt/latest/_static/operators/index.html)

+ Others
  + [CUDA](https://developer.nvidia.com/cuda-zone)
  + [NVIDIA/Model-Optimizer](https://github.com/NVIDIA/Model-Optimizer) (rebranded from "TensorRT Model Optimizer", Dec 2025)
  + [NVIDIA/TensorRT-Incubator](https://github.com/NVIDIA/TensorRT-Incubator)
  + [NVIDIA/TensorRT-LLM](https://github.com/NVIDIA/TensorRT-LLM)
  + [NVIDIA/TensorRT-Model-Connect](https://github.com/NVIDIA/TensorRT-Model-Connect), [TensorRT-RTX-EP-ABI](https://github.com/NVIDIA/TensorRT-RTX-EP-ABI)
  + [ONNX Model Zoo](https://github.com/onnx/models)
  + [ONNX Operators](https://github.com/onnx/onnx/blob/main/docs/Operators.md)
  + [ONNX Runtime](https://github.com/microsoft/onnxruntime)
  + [ONNX](https://github.com/onnx/onnx)
  + [Polygraphy API Reference](https://docs.nvidia.com/deeplearning/tensorrt/polygraphy/docs/index.html)
  + [Polygraphy document](https://github.com/NVIDIA/TensorRT/tree/main/tools/Polygraphy/polygraphy)
  + [pytorch/tensorrt](https://docs.pytorch.org/TensorRT/)
  + [tensorflow/tensorrt](https://github.com/tensorflow/tensorrt) (archived since Feb 2025, read-only)
  + [tensorrtx (Network API building)](https://github.com/wang-xinyu/tensorrtx)
  + [TREX](https://github.com/NVIDIA/TensorRT/tree/main/tools/experimental/trt-engine-explorer)
"""[1:]

# build_copyright(cookbook_path())

build_readme(cookbook_path(), ROOT_OUTLINE)

print("Finish")
