#!/usr/bin/env python3
# Template auto-generated by polygraphy [v0.33.0] on 05/07/22 at 07:20:08
# Generation Command: /usr/local/bin/polygraphy template trt-network model.onnx --output modifyNetwork.py
# Creates a TensorRT Network using the Network API.
from polygraphy import func
from polygraphy.backend.trt import NetworkFromOnnxPath
import tensorrt as trt

# Loaders
parse_network_from_onnx = NetworkFromOnnxPath('/work/gitlab/tensorrt-cookbook-in-chinese/08-Tool/Polygraphy/templateExample/model.onnx')

@func.extend(parse_network_from_onnx)
def load_network(builder, network, parser):
    pass # TODO: Set up the network here. This function should not return anything.
