rm ./*.onnx
python 01-CreateModel.py
python 02-CreateModelWithInitializer.py
python 03-IsolateSubgraph.py
python 04-ModifyModel.py
python 05-FoldModel.py
python 06-RemoveNode.py
python 07-BuildModelWithAPI.py
python 08-ReplaceNode.py
python 09-ShapeOperation.py
#rm ./*.onnx
